### ISSUE TITLE
add a function to reload conf when modifying conf.js without restarting server

### ISSUE THREAD

**Issue by Gotier** [nicodeur/QualityDashboard#1]
Hi Nicolas,

It may be usefull to add a function in server.js to reload the conf when you modify it. Otherwise currently I think you need to restart the server manually.

For example add this to "server.js" (as a node.js, i'm not sure of the syntax)
```
var reload = require('express-reload');

// path to reload
var configPath = __dirname + '/config/conf.js';

app.use(reload(configPath ));
```

Here is the source : [express-reload](https://www.npmjs.com/package/express-reload)

Best regards.

**Comment by nicodeur** [comment]
Hi @Gotier !

Yes it's a good idea. Do you want propose it as a pull request ?

Nico

2017-11-03 11:04 GMT+01:00 Gotier <notifications@github.com>:

**Comment by Gotier** [comment]
Finally, I use nodemon to reload the conf.

I make a tag (1.1.1) with the changes.

Gotier

**Comment by nicodeur** [comment]
Thanks @Gotier !

So, I close this issue.

Nicolas
